Repository SchoodEIP/Schood-API, pull requests merged in 2023-05, with the labels that each got.

#1 [MOD] Modified informations.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  infos/CODE_OF_CONDUCT.md
  infos/CONTRIBUTING.md
  infos/LICENSE
  infos/README.md
  infos/SECURITY.md
Labels: documentation

#3 Sprint1
  .env.template
  .gitignore
  README.md
  docker-compose.yml
  src/__tests__/launch.test.js
  src/__tests__/serverUtils/testServer.js
  src/__tests__/user/user.test.js
  src/config/.gitkeep
  src/config/db.config.js
  src/config/db.default.js
  src/config/db.js
  src/index.js
  src/middleware/.gitkeep
  src/middleware/access.js
  src/middleware/auth.js
  src/middleware/sanitize.js
  src/models/.gitkeep
  src/models/classes.js
  src/models/roles.js
  src/models/users.js
  src/package-lock.json
  src/package.json
  src/routes/adm/register.js
  src/routes/adm/router.js
  src/routes/router.js
  src/routes/user/login.js
  src/routes/user/router.js
  src/services/mailer.js
  src/setup.sh
  src/swagger.yaml
Labels: documentation, enhancement

#4 CI/CD Integration
  .env.template
  .github/ISSUE_TEMPLATE/pld_feature.yml
  .github/dependabot.yml
  .github/workflows/linter.yml
  .github/workflows/njsscan.yml
  .github/workflows/test_coverage.yml
  README.md
  src/__tests__/launch.test.js
  src/__tests__/routes/adm/register.test.js
  src/__tests__/routes/user/user.test.js
  src/__tests__/serverUtils/testServer.js
  src/__tests__/user/user.test.js
  src/config/db.default.js
  src/index.js
  src/middleware/access.js
  src/middleware/auth.js
  src/middleware/sanitize.js
  src/models/classes.js
  src/models/roles.js
  src/models/users.js
  src/package-lock.json
  src/package.json
  src/routes/adm/register.js
  src/routes/adm/router.js
  src/routes/user/login.js
  src/routes/user/router.js
  src/services/mailer.js
Labels: documentation, enhancement

#2 2.6.1
  .gitignore
  README.md
  src/__tests__/routes/admin/facility/facility.test.js
  src/models/facilities.js
  src/models/roles.js
  src/models/users.js
  src/routes/admin/facility/register.js
  src/routes/admin/facility/router.js
  src/routes/admin/router.js
  src/routes/router.js
  src/swagger.yaml
Labels: documentation, enhancement

#11 [MOD] Modified workflows on
  .github/workflows/codeql.yml
  .github/workflows/linter.yml
  .github/workflows/njsscan.yml
  .github/workflows/test_coverage.yml
Labels: enhancement
